# Generated by Django 4.1.2 on 2022-10-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('expertises', models.ManyToManyField(to='main_app.expertise')),
            ],
        ),
    ]
